<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('id' => '1','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '9','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-17 09:23:25','updated_at' => '2022-05-17 09:23:25','deleted_at' => NULL),
            array('id' => '2','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '13','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-17 11:17:47','updated_at' => '2022-05-17 11:17:47','deleted_at' => NULL),
            array('id' => '3','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '32','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-19 14:33:29','updated_at' => '2022-05-19 14:33:29','deleted_at' => NULL),
            array('id' => '4','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '34','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-19 14:36:08','updated_at' => '2022-07-07 05:58:48','deleted_at' => NULL),
            array('id' => '5','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '38','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-27 08:17:20','updated_at' => '2022-07-07 06:05:53','deleted_at' => NULL),
            array('id' => '6','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '41','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-29 11:02:10','updated_at' => '2022-07-07 06:13:46','deleted_at' => NULL),
            array('id' => '7','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '42','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-30 15:06:49','updated_at' => '2022-05-30 15:06:49','deleted_at' => NULL),
            array('id' => '8','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '44','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-05-30 15:38:29','updated_at' => '2022-07-07 06:23:09','deleted_at' => NULL),
            array('id' => '9','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '45','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 10:10:47','updated_at' => '2022-06-01 10:10:47','deleted_at' => NULL),
            array('id' => '10','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '49','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 10:47:10','updated_at' => '2022-06-01 10:47:10','deleted_at' => NULL),
            array('id' => '11','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '50','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 10:58:41','updated_at' => '2022-06-01 10:58:41','deleted_at' => NULL),
            array('id' => '12','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '52','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 11:10:46','updated_at' => '2022-06-01 11:10:46','deleted_at' => NULL),
            array('id' => '13','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '57','stock' => '1','visible' => '0','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 11:25:13','updated_at' => '2022-12-22 12:06:31','deleted_at' => NULL),
            array('id' => '14','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '59','stock' => '1','visible' => '0','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 11:33:03','updated_at' => '2022-12-22 12:06:28','deleted_at' => NULL),
            array('id' => '15','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '61','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-01 11:50:44','updated_at' => '2022-06-01 11:50:44','deleted_at' => NULL),
            array('id' => '16','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '63','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-02 09:42:49','updated_at' => '2022-06-02 09:42:49','deleted_at' => NULL),
            array('id' => '17','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '67','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 09:53:28','updated_at' => '2022-06-03 09:53:28','deleted_at' => NULL),
            array('id' => '18','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '71','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:04:08','updated_at' => '2022-06-03 10:04:08','deleted_at' => NULL),
            array('id' => '19','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '72','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:12:41','updated_at' => '2022-06-03 10:12:41','deleted_at' => NULL),
            array('id' => '20','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '73','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:19:16','updated_at' => '2022-06-03 10:19:16','deleted_at' => NULL),
            array('id' => '21','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '74','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:38:27','updated_at' => '2022-06-03 10:38:27','deleted_at' => NULL),
            array('id' => '22','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '78','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:46:10','updated_at' => '2022-06-03 10:46:10','deleted_at' => NULL),
            array('id' => '23','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '79','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 10:52:21','updated_at' => '2022-06-03 10:52:21','deleted_at' => NULL),
            array('id' => '24','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '83','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 11:00:33','updated_at' => '2022-07-07 05:47:36','deleted_at' => NULL),
            array('id' => '25','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '84','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-03 11:34:28','updated_at' => '2022-07-08 07:32:57','deleted_at' => '2022-07-08 07:32:57'),
            array('id' => '26','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '84','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-08 09:47:08','updated_at' => '2022-06-08 09:47:08','deleted_at' => NULL),
            array('id' => '27','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '86','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 18:55:42','updated_at' => '2022-06-09 18:55:42','deleted_at' => NULL),
            array('id' => '28','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '87','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 19:23:53','updated_at' => '2022-06-09 19:23:53','deleted_at' => NULL),
            array('id' => '29','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '88','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 19:36:29','updated_at' => '2022-06-09 19:36:29','deleted_at' => NULL),
            array('id' => '30','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '89','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 19:58:48','updated_at' => '2022-06-09 19:58:48','deleted_at' => NULL),
            array('id' => '31','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '90','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 20:06:01','updated_at' => '2022-06-09 20:06:01','deleted_at' => NULL),
            array('id' => '32','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '91','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:05:26','updated_at' => '2022-06-09 22:05:26','deleted_at' => NULL),
            array('id' => '33','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '93','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:10:09','updated_at' => '2022-06-09 22:10:09','deleted_at' => NULL),
            array('id' => '34','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '95','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:16:21','updated_at' => '2022-06-09 22:16:21','deleted_at' => NULL),
            array('id' => '35','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '97','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:20:54','updated_at' => '2022-06-09 22:20:54','deleted_at' => NULL),
            array('id' => '36','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '99','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:24:47','updated_at' => '2022-06-09 22:24:47','deleted_at' => NULL),
            array('id' => '37','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '101','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:29:36','updated_at' => '2022-06-09 22:29:36','deleted_at' => NULL),
            array('id' => '38','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '102','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:34:35','updated_at' => '2022-06-09 22:34:35','deleted_at' => NULL),
            array('id' => '39','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '103','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:41:55','updated_at' => '2022-06-09 22:41:55','deleted_at' => NULL),
            array('id' => '40','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '104','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-09 22:49:35','updated_at' => '2022-06-09 22:49:35','deleted_at' => NULL),
            array('id' => '41','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '106','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 08:45:41','updated_at' => '2022-06-12 08:45:41','deleted_at' => NULL),
            array('id' => '42','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '107','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 08:53:49','updated_at' => '2022-06-12 08:53:49','deleted_at' => NULL),
            array('id' => '43','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '108','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 09:00:16','updated_at' => '2022-06-12 09:00:16','deleted_at' => NULL),
            array('id' => '44','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '109','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 09:27:11','updated_at' => '2022-06-12 09:27:11','deleted_at' => NULL),
            array('id' => '45','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '113','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 10:12:10','updated_at' => '2022-06-12 10:12:10','deleted_at' => NULL),
            array('id' => '46','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '114','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 11:09:26','updated_at' => '2022-06-12 11:09:26','deleted_at' => NULL),
            array('id' => '47','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '115','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-12 11:19:41','updated_at' => '2022-06-12 11:19:41','deleted_at' => NULL),
            array('id' => '48','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '117','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 16:18:15','updated_at' => '2022-07-05 14:53:18','deleted_at' => NULL),
            array('id' => '49','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '121','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 16:54:45','updated_at' => '2022-07-05 15:01:58','deleted_at' => NULL),
            array('id' => '50','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '122','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 22:55:04','updated_at' => '2022-06-13 22:55:04','deleted_at' => NULL),
            array('id' => '51','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '123','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 22:58:37','updated_at' => '2022-06-13 22:58:37','deleted_at' => NULL),
            array('id' => '52','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '127','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:05:00','updated_at' => '2022-07-07 14:06:52','deleted_at' => '2022-07-07 14:06:52'),
            array('id' => '53','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '131','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:11:46','updated_at' => '2022-06-13 23:11:46','deleted_at' => NULL),
            array('id' => '54','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '132','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:17:58','updated_at' => '2022-06-13 23:17:58','deleted_at' => NULL),
            array('id' => '55','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '133','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:26:20','updated_at' => '2022-06-13 23:26:20','deleted_at' => NULL),
            array('id' => '56','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '134','stock' => '1','visible' => '0','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:33:33','updated_at' => '2023-09-10 10:28:49','deleted_at' => NULL),
            array('id' => '57','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '138','stock' => '1','visible' => '0','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:44:34','updated_at' => '2023-09-10 10:28:46','deleted_at' => NULL),
            array('id' => '58','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '140','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:49:52','updated_at' => '2022-06-13 23:49:52','deleted_at' => NULL),
            array('id' => '59','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '147','stock' => '1','visible' => '0','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-13 23:55:51','updated_at' => '2022-08-20 16:10:33','deleted_at' => NULL),
            array('id' => '60','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '149','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:01:10','updated_at' => '2022-06-14 00:01:10','deleted_at' => NULL),
            array('id' => '61','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '151','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:06:52','updated_at' => '2022-06-14 00:06:52','deleted_at' => NULL),
            array('id' => '62','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '223','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:16:48','updated_at' => '2023-01-12 13:42:04','deleted_at' => NULL),
            array('id' => '63','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '224','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:21:41','updated_at' => '2023-01-12 13:41:50','deleted_at' => NULL),
            array('id' => '64','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '222','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:28:20','updated_at' => '2023-01-12 13:41:28','deleted_at' => NULL),
            array('id' => '65','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '164','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:40:55','updated_at' => '2022-06-14 00:40:55','deleted_at' => NULL),
            array('id' => '66','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '168','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:48:17','updated_at' => '2022-06-14 00:48:17','deleted_at' => NULL),
            array('id' => '67','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '170','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 00:53:34','updated_at' => '2022-06-14 00:53:34','deleted_at' => NULL),
            array('id' => '68','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '172','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-14 01:00:44','updated_at' => '2022-06-14 01:00:44','deleted_at' => NULL),
            array('id' => '69','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '173','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 06:27:19','updated_at' => '2022-06-16 06:27:19','deleted_at' => NULL),
            array('id' => '70','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '174','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 06:39:20','updated_at' => '2022-06-16 06:39:20','deleted_at' => NULL),
            array('id' => '71','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '176','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 07:02:34','updated_at' => '2022-06-16 07:02:34','deleted_at' => NULL),
            array('id' => '72','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '179','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 07:50:50','updated_at' => '2022-06-16 07:50:50','deleted_at' => NULL),
            array('id' => '73','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '186','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 08:06:28','updated_at' => '2022-06-16 08:06:28','deleted_at' => NULL),
            array('id' => '74','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '188','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 08:21:44','updated_at' => '2022-06-16 08:21:44','deleted_at' => NULL),
            array('id' => '75','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '191','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 08:39:33','updated_at' => '2022-06-16 08:39:33','deleted_at' => NULL),
            array('id' => '76','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '196','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-06-16 08:52:03','updated_at' => '2022-06-16 08:52:03','deleted_at' => NULL),
            array('id' => '77','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '156','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 10:54:23','updated_at' => '2022-07-05 10:54:23','deleted_at' => NULL),
            array('id' => '78','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '154','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 11:06:17','updated_at' => '2022-07-05 11:06:17','deleted_at' => NULL),
            array('id' => '79','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '159','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 11:22:59','updated_at' => '2022-07-05 11:22:59','deleted_at' => NULL),
            array('id' => '80','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '157','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 11:23:03','updated_at' => '2022-07-05 11:23:03','deleted_at' => NULL),
            array('id' => '81','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '162','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 11:45:48','updated_at' => '2022-07-05 11:45:48','deleted_at' => NULL),
            array('id' => '82','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '160','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 11:45:58','updated_at' => '2022-07-05 11:45:58','deleted_at' => NULL),
            array('id' => '83','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '116','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 14:53:13','updated_at' => '2022-07-05 14:53:13','deleted_at' => NULL),
            array('id' => '84','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '120','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 15:01:54','updated_at' => '2022-07-05 15:01:54','deleted_at' => NULL),
            array('id' => '85','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '163','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-05 15:15:07','updated_at' => '2022-07-05 15:15:07','deleted_at' => NULL),
            array('id' => '86','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '167','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-06 07:22:50','updated_at' => '2022-07-06 07:22:50','deleted_at' => NULL),
            array('id' => '87','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '169','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 05:24:13','updated_at' => '2022-07-07 05:24:13','deleted_at' => NULL),
            array('id' => '88','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '171','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 05:31:01','updated_at' => '2022-07-07 05:31:01','deleted_at' => NULL),
            array('id' => '89','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '82','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 05:47:31','updated_at' => '2022-07-07 05:47:31','deleted_at' => NULL),
            array('id' => '90','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '33','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 05:58:42','updated_at' => '2022-07-07 05:58:42','deleted_at' => NULL),
            array('id' => '91','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '37','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 06:05:44','updated_at' => '2022-07-07 06:05:44','deleted_at' => NULL),
            array('id' => '92','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '40','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 06:13:42','updated_at' => '2022-07-07 06:13:42','deleted_at' => NULL),
            array('id' => '93','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '43','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 06:23:00','updated_at' => '2022-07-07 06:23:00','deleted_at' => NULL),
            array('id' => '94','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '51','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2022-07-07 06:33:21','updated_at' => '2022-07-07 06:33:21','deleted_at' => NULL),
            array('id' => '95','external_id' => NULL,'name' => NULL,'sku' => NULL,'gtin' => NULL,'price' => '0.00','rental_price' => NULL,'original_price' => NULL,'sale_price' => NULL,'sale' => '0','sale_from' => NULL,'sale_to' => NULL,'file_id' => '226','stock' => '1','visible' => '1','sort_priority' => '0','rating' => '0.00','sizes_type' => NULL,'sizes_standard' => 'EU','created_at' => '2023-09-11 07:01:54','updated_at' => '2023-09-11 07:01:54','deleted_at' => NULL)
        );

        DB::table('products')->insert($products);
	}
}
